title: Piper Dakota Sim
description: "A custom PA-28-235 flight simulator build."
theme: just-the-docs
show_downloads: true

# Enables left-side navigation
nav_order: 1
search_enabled: true

# Sidebar navigation structure
nav:
  - title: "Home"
    url: /
  - title: "Hardware"
    url: hardware.md
  - title: "Software"
    url: software.md
  - title: "Pricing"
    url: pricing.md
  - title: "Build Details"
    url: build.md

# Plugins for SEO and sitemap
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
